const names = [
    "Second Horizons",
    "Shadow Falls Camp",
    "American Heritage",
    "Money Creek",
    "Fort Worden",
    "Heart O’ the Hills",
    "Expo Center",
    "Buckler River",
    "Silver Lake Camp",
    "Southwood’s",
    "The Captain",
    "Camp Northway",
    "Olympia Camp",
    "The Pathfinder",
    "Phantom Lake",
    "Camp Pinehurst",
    "The Quest",
    "Red Arrow",
    "Chowder",
    "Chuckwagon",
    "The Colonel",
    "New Beginnings",
    "Pali Adventures",
    "Pleasant Valley",
    "Point O’Pines",
    "Point X Camp",
    "The Lake Camps",
    "Rawhide Ranch",
    "Red Arrow Camp",
    "Spirit -in -the - Woods",
    "Sunny Days",
    "Tall Pines Camp",
    "The Great Outdoors",
    "West Canyon",
    "Whispering Pines",
    "Caravan Outfitter",
    "Cruise America RV Rental",
    "Kia Campground",
    "Peace Vans",
    "Tacoma KOA Journey",
    "Cruise America"
];

const descriptions = [
    "Peaceful",
    "Picturesque",
    "Unspoiled",
    "Vibrant",
    "Lively",
    "Inspiring",
    "Homey",
    "Fresh",
    "Fascinating",
    "Enchanting",
    "Cosmopolitan",
    "Charming",
    "Calm",
    "Bustling",
    "Beautiful",
    "Alive",
    "Nightmarish",
    "Polluted",
    "Stormy",
    "Touristy",
    "Ugly",
    "Ancient",
    "Contemporary",
    "Majestic",
    "Magical",
    "Quiet",
    "Traditional",
    "Mystical"
];

const cities = [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Ottawa",
    "Edmonton",
    "Calgary",
    "Quebec",
    "Winnipeg",
    "Hamilton",
    "London",
    "Kitchener",
    "St Catherines-Niagara",
    "Halifax",
    "Victoria",
    "Windsor",
    "Oshawa",
    "Saskatoon",
    "Regina",
    "St John's",
    "Sudbury"
];

exports.names = names;
exports.descriptions = descriptions;
exports.cities = cities;